M48
; DRILL file {KiCad 7.0.10} date Friday, April 12, 2024 at 10:07:16 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-12T22:07:16+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X139.1Y-33.25
X139.1Y-135.25
X158.1Y-33.25
X194.1Y-33.25
X194.1Y-135.25
X213.1Y-33.25
M30
